{
    "type": "bundle",
    "id": "bundle--af09ae79-2c32-4310-8912-0d4ede2d35cd",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--46f62c5c-fd45-4c9e-bb86-ba970197d8ef",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2025-02-27T01:47:32.926189Z",
            "modified": "2025-02-27T01:47:32.926189Z",
            "name": "CVE-2022-49089",
            "description": "In the Linux kernel, the following vulnerability has been resolved:\n\nIB/rdmavt: add lock to call to rvt_error_qp to prevent a race condition\n\nThe documentation of the function rvt_error_qp says both r_lock and s_lock\nneed to be held when calling that function.  It also asserts using lockdep\nthat both of those locks are held.  However, the commit I referenced in\nFixes accidentally makes the call to rvt_error_qp in rvt_ruc_loopback no\nlonger covered by r_lock.  This results in the lockdep assertion failing\nand also possibly in a race condition.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2022-49089"
                }
            ]
        }
    ]
}